default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: d1kbqc0rmonfoc
  username: veewgswrtlwgfv
  host: ec2-44-209-158-64.compute-1.amazonaws.com
  password: 65bbbac8efb340484b150a711bb733933184485e0c1cc0a44552f284cc3750c7